### ISSUE TITLE
Score screen bug

### ISSUE THREAD

**Issue by pony1487** [david-p-burton/WobbleBeat#1]
After going to Score screen and coming back to main menu, once player starts a new game, the instructions are still displaying on the screen.

I think it is something to do with this:
case 4:
			{
				cp5.remove("Player Name");
				text("Press x to go back", (width / 2), (float)(height * 0.85));
				if(!scoresLoaded)
				{
					db.loadScores();
					
					scoresLoaded = true;
				}
				else
				{
					db.printScores();
				}
				
				if(checkKey('x'))
				{
					gameState = 0;
				}

				break;
			}

**Comment by david-p-burton** [comment]
I think that may be because the Instruction object controls is not being removed from the GameObjects ArrayList. I will check it out now shortly
